select * from PURCHBOOKTRANS_RU
join PURCHBOOKTABLE_RU
on PURCHBOOKTABLE_RU.RECID = PURCHBOOKTRANS_RU.PURCHBOOKTABLE_RU
where 
PURCHBOOKTABLE_RU.ClosingDate >=  @fromdate
and PURCHBOOKTABLE_RU.ClosingDate <=  @todate
order by PURCHBOOKTRANS_RU.RecId
